@startuml
left to right direction
skinparam packageStyle rectangle
actor Pfleger
rectangle Web-Applikation {
 Pfleger -- (Klienten-Historie durchsuchen)
 Pfleger -- (Klient auswählen) 
 (Stichwort- / Volltextsuche) --|> (Klienten-Historie durchsuchen)
 (Feste Kriterien- / Tagsuche) --|> (Klienten-Historie durchsuchen)
 (Klienten-Historie durchsuchen) .-> (Klient auswählen) : include
}
@enduml